//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvContrato
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OC_IBK.OC_PERSONA", Namespace="http://schemas.datacontract.org/2004/07/EntidadesClases.CustomModelEntities")]
    public partial class OC_IBKOC_PERSONA : object
    {
        
        private string CELULARField;
        
        private string CIField;
        
        private string CICField;
        
        private string COMPLEMENTOField;
        
        private string CORREOField;
        
        private string DIRECCIONField;
        
        private string ESTADO_CIVILField;
        
        private string EXTENSIONField;
        
        private System.Nullable<System.DateTime> FECHA_NACIMIENTOField;
        
        private byte[] IMAGENField;
        
        private string MATERNOField;
        
        private string NACIONALIDADField;
        
        private string NOMBREField;
        
        private string NUMERO_DIRECCIONField;
        
        private string OCUPACIONField;
        
        private string PATERNOField;
        
        private string PROFESIONField;
        
        private string SEXOField;
        
        private string TELEFONOField;
        
        private string TIPO_DIRECCIONField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CELULAR
        {
            get
            {
                return this.CELULARField;
            }
            set
            {
                this.CELULARField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CI
        {
            get
            {
                return this.CIField;
            }
            set
            {
                this.CIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIC
        {
            get
            {
                return this.CICField;
            }
            set
            {
                this.CICField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPLEMENTO
        {
            get
            {
                return this.COMPLEMENTOField;
            }
            set
            {
                this.COMPLEMENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO
        {
            get
            {
                return this.CORREOField;
            }
            set
            {
                this.CORREOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECCION
        {
            get
            {
                return this.DIRECCIONField;
            }
            set
            {
                this.DIRECCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO_CIVIL
        {
            get
            {
                return this.ESTADO_CIVILField;
            }
            set
            {
                this.ESTADO_CIVILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXTENSION
        {
            get
            {
                return this.EXTENSIONField;
            }
            set
            {
                this.EXTENSIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_NACIMIENTO
        {
            get
            {
                return this.FECHA_NACIMIENTOField;
            }
            set
            {
                this.FECHA_NACIMIENTOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] IMAGEN
        {
            get
            {
                return this.IMAGENField;
            }
            set
            {
                this.IMAGENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MATERNO
        {
            get
            {
                return this.MATERNOField;
            }
            set
            {
                this.MATERNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NACIONALIDAD
        {
            get
            {
                return this.NACIONALIDADField;
            }
            set
            {
                this.NACIONALIDADField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE
        {
            get
            {
                return this.NOMBREField;
            }
            set
            {
                this.NOMBREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMERO_DIRECCION
        {
            get
            {
                return this.NUMERO_DIRECCIONField;
            }
            set
            {
                this.NUMERO_DIRECCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OCUPACION
        {
            get
            {
                return this.OCUPACIONField;
            }
            set
            {
                this.OCUPACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PATERNO
        {
            get
            {
                return this.PATERNOField;
            }
            set
            {
                this.PATERNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROFESION
        {
            get
            {
                return this.PROFESIONField;
            }
            set
            {
                this.PROFESIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEXO
        {
            get
            {
                return this.SEXOField;
            }
            set
            {
                this.SEXOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEFONO
        {
            get
            {
                return this.TELEFONOField;
            }
            set
            {
                this.TELEFONOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_DIRECCION
        {
            get
            {
                return this.TIPO_DIRECCIONField;
            }
            set
            {
                this.TIPO_DIRECCIONField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CREDENCIALES_AUTH", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    public partial class CREDENCIALES_AUTH : object
    {
        
        private string IPField;
        
        private string PASSWORDField;
        
        private string USUARIOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASSWORD
        {
            get
            {
                return this.PASSWORDField;
            }
            set
            {
                this.PASSWORDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USUARIO
        {
            get
            {
                return this.USUARIOField;
            }
            set
            {
                this.USUARIOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OC_IBK.ResponseAfiliacionIBK", Namespace="http://schemas.datacontract.org/2004/07/EntidadesClases.CustomModelEntities")]
    public partial class OC_IBKResponseAfiliacionIBK : object
    {
        
        private string CODIGO_ERRORField;
        
        private string ERROR_TECNICOField;
        
        private long ID_AFILIACIONField;
        
        private string ID_CLIENTEField;
        
        private string MENSAJE_ERRORField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_ERROR
        {
            get
            {
                return this.CODIGO_ERRORField;
            }
            set
            {
                this.CODIGO_ERRORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERROR_TECNICO
        {
            get
            {
                return this.ERROR_TECNICOField;
            }
            set
            {
                this.ERROR_TECNICOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_AFILIACION
        {
            get
            {
                return this.ID_AFILIACIONField;
            }
            set
            {
                this.ID_AFILIACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_CLIENTE
        {
            get
            {
                return this.ID_CLIENTEField;
            }
            set
            {
                this.ID_CLIENTEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENSAJE_ERROR
        {
            get
            {
                return this.MENSAJE_ERRORField;
            }
            set
            {
                this.MENSAJE_ERRORField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OC_IBK.ResponseDocumentoIBK", Namespace="http://schemas.datacontract.org/2004/07/EntidadesClases.CustomModelEntities")]
    public partial class OC_IBKResponseDocumentoIBK : object
    {
        
        private string CODIGO_ERRORField;
        
        private string ERROR_TECNICOField;
        
        private byte[] IMAGENField;
        
        private string MENSAJE_ERRORField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_ERROR
        {
            get
            {
                return this.CODIGO_ERRORField;
            }
            set
            {
                this.CODIGO_ERRORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERROR_TECNICO
        {
            get
            {
                return this.ERROR_TECNICOField;
            }
            set
            {
                this.ERROR_TECNICOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] IMAGEN
        {
            get
            {
                return this.IMAGENField;
            }
            set
            {
                this.IMAGENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENSAJE_ERROR
        {
            get
            {
                return this.MENSAJE_ERRORField;
            }
            set
            {
                this.MENSAJE_ERRORField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estacion.Response", Namespace="http://schemas.datacontract.org/2004/07/EntidadesClases.CustomModelEntities")]
    public partial class EstacionResponse : object
    {
        
        private string CODIGO_ERRORField;
        
        private string ERROR_TECNICOField;
        
        private string MENSAJE_ERRORField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_ERROR
        {
            get
            {
                return this.CODIGO_ERRORField;
            }
            set
            {
                this.CODIGO_ERRORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERROR_TECNICO
        {
            get
            {
                return this.ERROR_TECNICOField;
            }
            set
            {
                this.ERROR_TECNICOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENSAJE_ERROR
        {
            get
            {
                return this.MENSAJE_ERRORField;
            }
            set
            {
                this.MENSAJE_ERRORField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estacion.ReporteDesafiliacion", Namespace="http://schemas.datacontract.org/2004/07/EntidadesClases.CustomModelEntities")]
    public partial class EstacionReporteDesafiliacion : object
    {
        
        private string CERTIFICADOField;
        
        private string CIField;
        
        private string CUENTA_TARJETAField;
        
        private bool ESTADO_AFILIACIONField;
        
        private System.DateTime FECHA_DESAFILIACIONField;
        
        private string NOMBREField;
        
        private string TIPO_DESAFILIACIONField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CERTIFICADO
        {
            get
            {
                return this.CERTIFICADOField;
            }
            set
            {
                this.CERTIFICADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CI
        {
            get
            {
                return this.CIField;
            }
            set
            {
                this.CIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUENTA_TARJETA
        {
            get
            {
                return this.CUENTA_TARJETAField;
            }
            set
            {
                this.CUENTA_TARJETAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ESTADO_AFILIACION
        {
            get
            {
                return this.ESTADO_AFILIACIONField;
            }
            set
            {
                this.ESTADO_AFILIACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA_DESAFILIACION
        {
            get
            {
                return this.FECHA_DESAFILIACIONField;
            }
            set
            {
                this.FECHA_DESAFILIACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE
        {
            get
            {
                return this.NOMBREField;
            }
            set
            {
                this.NOMBREField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_DESAFILIACION
        {
            get
            {
                return this.TIPO_DESAFILIACIONField;
            }
            set
            {
                this.TIPO_DESAFILIACIONField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srvContrato.IServicioAfiliacionAuth")]
    public interface IServicioAfiliacionAuth
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAfiliacionAuth/SaveAfiliacion", ReplyAction="http://tempuri.org/IServicioAfiliacionAuth/SaveAfiliacionResponse")]
        srvContrato.OC_IBKResponseAfiliacionIBK SaveAfiliacion(srvContrato.OC_IBKOC_PERSONA objPersona, string cuenta, string IdProducto, srvContrato.CREDENCIALES_AUTH objCredenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAfiliacionAuth/SaveAfiliacion", ReplyAction="http://tempuri.org/IServicioAfiliacionAuth/SaveAfiliacionResponse")]
        System.Threading.Tasks.Task<srvContrato.OC_IBKResponseAfiliacionIBK> SaveAfiliacionAsync(srvContrato.OC_IBKOC_PERSONA objPersona, string cuenta, string IdProducto, srvContrato.CREDENCIALES_AUTH objCredenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAfiliacionAuth/GetFileCertificado", ReplyAction="http://tempuri.org/IServicioAfiliacionAuth/GetFileCertificadoResponse")]
        srvContrato.OC_IBKResponseDocumentoIBK GetFileCertificado(string IdPersona, long IdAfiliacion, string IdProducto, srvContrato.CREDENCIALES_AUTH objCredenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAfiliacionAuth/GetFileCertificado", ReplyAction="http://tempuri.org/IServicioAfiliacionAuth/GetFileCertificadoResponse")]
        System.Threading.Tasks.Task<srvContrato.OC_IBKResponseDocumentoIBK> GetFileCertificadoAsync(string IdPersona, long IdAfiliacion, string IdProducto, srvContrato.CREDENCIALES_AUTH objCredenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAfiliacionAuth/UpdateDatosCuenta", ReplyAction="http://tempuri.org/IServicioAfiliacionAuth/UpdateDatosCuentaResponse")]
        srvContrato.OC_IBKResponseAfiliacionIBK UpdateDatosCuenta(long idAfiliacion, string cuentaNueva, srvContrato.CREDENCIALES_AUTH objCredenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAfiliacionAuth/UpdateDatosCuenta", ReplyAction="http://tempuri.org/IServicioAfiliacionAuth/UpdateDatosCuentaResponse")]
        System.Threading.Tasks.Task<srvContrato.OC_IBKResponseAfiliacionIBK> UpdateDatosCuentaAsync(long idAfiliacion, string cuentaNueva, srvContrato.CREDENCIALES_AUTH objCredenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAfiliacionAuth/Desafiliacion", ReplyAction="http://tempuri.org/IServicioAfiliacionAuth/DesafiliacionResponse")]
        srvContrato.EstacionResponse Desafiliacion(string carnet, string extension, string com, string cuenta, string descripcionDesafiliacion, string idProducto, srvContrato.CREDENCIALES_AUTH objCredenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAfiliacionAuth/Desafiliacion", ReplyAction="http://tempuri.org/IServicioAfiliacionAuth/DesafiliacionResponse")]
        System.Threading.Tasks.Task<srvContrato.EstacionResponse> DesafiliacionAsync(string carnet, string extension, string com, string cuenta, string descripcionDesafiliacion, string idProducto, srvContrato.CREDENCIALES_AUTH objCredenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAfiliacionAuth/ReporteDesafiliacion", ReplyAction="http://tempuri.org/IServicioAfiliacionAuth/ReporteDesafiliacionResponse")]
        srvContrato.EstacionReporteDesafiliacion[] ReporteDesafiliacion(string usuario, srvContrato.CREDENCIALES_AUTH objCredenciales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAfiliacionAuth/ReporteDesafiliacion", ReplyAction="http://tempuri.org/IServicioAfiliacionAuth/ReporteDesafiliacionResponse")]
        System.Threading.Tasks.Task<srvContrato.EstacionReporteDesafiliacion[]> ReporteDesafiliacionAsync(string usuario, srvContrato.CREDENCIALES_AUTH objCredenciales);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServicioAfiliacionAuthChannel : srvContrato.IServicioAfiliacionAuth, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioAfiliacionAuthClient : System.ServiceModel.ClientBase<srvContrato.IServicioAfiliacionAuth>, srvContrato.IServicioAfiliacionAuth
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioAfiliacionAuthClient() : 
                base(ServicioAfiliacionAuthClient.GetDefaultBinding(), ServicioAfiliacionAuthClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioSwampHttpEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAfiliacionAuthClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioAfiliacionAuthClient.GetBindingForEndpoint(endpointConfiguration), ServicioAfiliacionAuthClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAfiliacionAuthClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioAfiliacionAuthClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAfiliacionAuthClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioAfiliacionAuthClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAfiliacionAuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public srvContrato.OC_IBKResponseAfiliacionIBK SaveAfiliacion(srvContrato.OC_IBKOC_PERSONA objPersona, string cuenta, string IdProducto, srvContrato.CREDENCIALES_AUTH objCredenciales)
        {
            return base.Channel.SaveAfiliacion(objPersona, cuenta, IdProducto, objCredenciales);
        }
        
        public System.Threading.Tasks.Task<srvContrato.OC_IBKResponseAfiliacionIBK> SaveAfiliacionAsync(srvContrato.OC_IBKOC_PERSONA objPersona, string cuenta, string IdProducto, srvContrato.CREDENCIALES_AUTH objCredenciales)
        {
            return base.Channel.SaveAfiliacionAsync(objPersona, cuenta, IdProducto, objCredenciales);
        }
        
        public srvContrato.OC_IBKResponseDocumentoIBK GetFileCertificado(string IdPersona, long IdAfiliacion, string IdProducto, srvContrato.CREDENCIALES_AUTH objCredenciales)
        {
            return base.Channel.GetFileCertificado(IdPersona, IdAfiliacion, IdProducto, objCredenciales);
        }
        
        public System.Threading.Tasks.Task<srvContrato.OC_IBKResponseDocumentoIBK> GetFileCertificadoAsync(string IdPersona, long IdAfiliacion, string IdProducto, srvContrato.CREDENCIALES_AUTH objCredenciales)
        {
            return base.Channel.GetFileCertificadoAsync(IdPersona, IdAfiliacion, IdProducto, objCredenciales);
        }
        
        public srvContrato.OC_IBKResponseAfiliacionIBK UpdateDatosCuenta(long idAfiliacion, string cuentaNueva, srvContrato.CREDENCIALES_AUTH objCredenciales)
        {
            return base.Channel.UpdateDatosCuenta(idAfiliacion, cuentaNueva, objCredenciales);
        }
        
        public System.Threading.Tasks.Task<srvContrato.OC_IBKResponseAfiliacionIBK> UpdateDatosCuentaAsync(long idAfiliacion, string cuentaNueva, srvContrato.CREDENCIALES_AUTH objCredenciales)
        {
            return base.Channel.UpdateDatosCuentaAsync(idAfiliacion, cuentaNueva, objCredenciales);
        }
        
        public srvContrato.EstacionResponse Desafiliacion(string carnet, string extension, string com, string cuenta, string descripcionDesafiliacion, string idProducto, srvContrato.CREDENCIALES_AUTH objCredenciales)
        {
            return base.Channel.Desafiliacion(carnet, extension, com, cuenta, descripcionDesafiliacion, idProducto, objCredenciales);
        }
        
        public System.Threading.Tasks.Task<srvContrato.EstacionResponse> DesafiliacionAsync(string carnet, string extension, string com, string cuenta, string descripcionDesafiliacion, string idProducto, srvContrato.CREDENCIALES_AUTH objCredenciales)
        {
            return base.Channel.DesafiliacionAsync(carnet, extension, com, cuenta, descripcionDesafiliacion, idProducto, objCredenciales);
        }
        
        public srvContrato.EstacionReporteDesafiliacion[] ReporteDesafiliacion(string usuario, srvContrato.CREDENCIALES_AUTH objCredenciales)
        {
            return base.Channel.ReporteDesafiliacion(usuario, objCredenciales);
        }
        
        public System.Threading.Tasks.Task<srvContrato.EstacionReporteDesafiliacion[]> ReporteDesafiliacionAsync(string usuario, srvContrato.CREDENCIALES_AUTH objCredenciales)
        {
            return base.Channel.ReporteDesafiliacionAsync(usuario, objCredenciales);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioSwampHttpEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioSwampHttpEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://devcrs02:3007/CRSclic.AfiliacionIBK.Core/ServicioAfiliacionAuth.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioAfiliacionAuthClient.GetBindingForEndpoint(EndpointConfiguration.ServicioSwampHttpEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioAfiliacionAuthClient.GetEndpointAddress(EndpointConfiguration.ServicioSwampHttpEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioSwampHttpEndPoint,
        }
    }
}
